name: facebook_ui
description: This app is a clone to the facebook UI inspired from "Marcus Ng" youtube channel from this link "https://www.youtube.com/watch?v=HvLb5gdUfDE&t=2101s" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.2+1
  material_design_icons_flutter: ^4.0.5555

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 